"""initial schema

Revision ID: 0001
Revises: (none)
Create Date: 2026-10-08
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('object_type', sa.String(length=48), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('object_revision', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('before_digest', sa.String(length=80), nullable=True),
    sa.Column('after_digest', sa.String(length=80), nullable=True),
    sa.Column('scope_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_correlation', 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_control_id'), 'audit_events', ['control_id'], unique=False)
    op.create_index('ix_audit_object', 'audit_events', ['object_type', 'object_id'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_digest', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_fixture_sets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_digest', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scopes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('native_id', sa.String(length=512), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=True),
    sa.Column('business_owner', sa.String(length=256), nullable=True),
    sa.Column('application', sa.String(length=128), nullable=True),
    sa.Column('is_management_account', sa.Boolean(), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'native_id', name='uq_scope_native')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('approval_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('subject_digest', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_subject', 'approval_decisions', ['subject_type', 'subject_id'], unique=False)
    op.create_table('controls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('operational_owner', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('governance_settings',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('resource_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('application', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=256), nullable=True),
    sa.Column('criticality', sa.String(length=32), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['inventory_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'resource_id', name='uq_resource_in_snapshot')
    )
    op.create_index(op.f('ix_resource_snapshots_snapshot_id'), 'resource_snapshots', ['snapshot_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', 'scope_id', name='uq_role_assignment')
    )
    op.create_table('work_references',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('owner_team', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('external_system', sa.String(length=64), nullable=True),
    sa.Column('external_ref', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('related_type', sa.String(length=64), nullable=False),
    sa.Column('related_id', sa.String(length=64), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_table('control_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('security_objective', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('providers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applicability_criteria', sa.Text(), nullable=False),
    sa.Column('security_owner', sa.String(length=256), nullable=False),
    sa.Column('engineering_owner', sa.String(length=256), nullable=False),
    sa.Column('framework_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exception_eligible', sa.Boolean(), nullable=False),
    sa.Column('prevention_boundary', sa.Text(), nullable=False),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('content_digest', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'revision', name='uq_control_revision')
    )
    op.create_index(op.f('ix_control_revisions_control_id'), 'control_revisions', ['control_id'], unique=False)
    op.create_table('implementations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('mechanism_role', sa.String(length=64), nullable=False),
    sa.Column('management', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_implementations_control_id'), 'implementations', ['control_id'], unique=False)
    op.create_table('readiness_evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('application', sa.String(length=128), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('prerequisite', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=512), nullable=True),
    sa.Column('provided_by', sa.String(length=256), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_evidence_control_id'), 'readiness_evidence', ['control_id'], unique=False)
    op.create_table('rollout_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('target_scope_id', sa.String(length=64), nullable=False),
    sa.Column('implementation_revision_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pause_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prerequisite_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deployment_instructions', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('state_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rollout_plans_control_id'), 'rollout_plans', ['control_id'], unique=False)
    op.create_table('change_packages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('package_revision', sa.Integer(), nullable=False),
    sa.Column('through_stage', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest_digest', sa.String(length=80), nullable=False),
    sa.Column('gate_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['rollout_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'package_revision', name='uq_package_revision')
    )
    op.create_index(op.f('ix_change_packages_control_id'), 'change_packages', ['control_id'], unique=False)
    op.create_index(op.f('ix_change_packages_plan_id'), 'change_packages', ['plan_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lineage_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('renews_exception_id', sa.String(length=64), nullable=True),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('implementation_id', sa.String(length=64), nullable=True),
    sa.Column('binding_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requester_id', sa.String(length=64), nullable=False),
    sa.Column('application', sa.String(length=128), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('business_justification', sa.Text(), nullable=False),
    sa.Column('technical_justification', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('granularity', sa.String(length=16), nullable=False),
    sa.Column('resource_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('principal_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_owner', sa.String(length=256), nullable=False),
    sa.Column('compensating_controls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('governance_status', sa.String(length=24), nullable=False),
    sa.Column('native_status', sa.String(length=24), nullable=False),
    sa.Column('representability', sa.String(length=40), nullable=False),
    sa.Column('representability_reason', sa.Text(), nullable=False),
    sa.Column('native_representation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('native_expiry_supported', sa.Boolean(), nullable=False),
    sa.Column('native_observed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('native_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('native_provenance', sa.String(length=32), nullable=True),
    sa.Column('work_ref', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['implementation_id'], ['implementations.id'], ),
    sa.ForeignKeyConstraint(['renews_exception_id'], ['exceptions.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_control_id'), 'exceptions', ['control_id'], unique=False)
    op.create_index(op.f('ix_exceptions_lineage_id'), 'exceptions', ['lineage_id'], unique=False)
    op.create_table('implementation_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('implementation_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('control_revision_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('policy_kind', sa.String(length=64), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=False),
    sa.Column('pinned_version', sa.String(length=64), nullable=True),
    sa.Column('content_digest', sa.String(length=80), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assignment_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('native_document', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capability_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_revision_id'], ['control_revisions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['implementation_id'], ['implementations.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('implementation_id', 'revision', name='uq_impl_revision')
    )
    op.create_index(op.f('ix_implementation_revisions_implementation_id'), 'implementation_revisions', ['implementation_id'], unique=False)
    op.create_table('assessment_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('control_revision_id', sa.String(length=64), nullable=False),
    sa.Column('implementation_revision_id', sa.String(length=64), nullable=False),
    sa.Column('target_scope_id', sa.String(length=64), nullable=False),
    sa.Column('inventory_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('request_fixture_set_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evaluator_id', sa.String(length=128), nullable=True),
    sa.Column('evaluator_version', sa.String(length=32), nullable=True),
    sa.Column('disclosure', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_digest', sa.String(length=80), nullable=False),
    sa.Column('rollup', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_digest', sa.String(length=80), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['control_revision_id'], ['control_revisions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['implementation_revision_id'], ['implementation_revisions.id'], ),
    sa.ForeignKeyConstraint(['inventory_snapshot_id'], ['inventory_snapshots.id'], ),
    sa.ForeignKeyConstraint(['request_fixture_set_id'], ['request_fixture_sets.id'], ),
    sa.ForeignKeyConstraint(['target_scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    op.create_index(op.f('ix_assessment_runs_control_id'), 'assessment_runs', ['control_id'], unique=False)
    op.create_table('handoff_bundles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('package_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('bundle_digest', sa.String(length=80), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_digests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('export_path', sa.String(length=1024), nullable=True),
    sa.Column('export_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exported_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['exported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['change_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoff_bundles_bundle_digest'), 'handoff_bundles', ['bundle_digest'], unique=False)
    op.create_index(op.f('ix_handoff_bundles_package_id'), 'handoff_bundles', ['package_id'], unique=False)
    op.create_table('implementation_validations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('implementation_revision_id', sa.String(length=64), nullable=False),
    sa.Column('revision_digest', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('evaluator_id', sa.String(length=128), nullable=True),
    sa.Column('evaluator_version', sa.String(length=32), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('possible_duplicates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('integration_ready', sa.Boolean(), nullable=False),
    sa.Column('integration_blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validator_version', sa.String(length=32), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['implementation_revision_id'], ['implementation_revisions.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    op.create_index(op.f('ix_implementation_validations_implementation_revision_id'), 'implementation_validations', ['implementation_revision_id'], unique=False)
    op.create_table('policy_bindings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=True),
    sa.Column('implementation_revision_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('binding_kind', sa.String(length=48), nullable=False),
    sa.Column('native_id', sa.String(length=512), nullable=False),
    sa.Column('definition_ref', sa.String(length=512), nullable=False),
    sa.Column('definition_digest', sa.String(length=80), nullable=True),
    sa.Column('target_scope_id', sa.String(length=64), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_repository', sa.String(length=512), nullable=True),
    sa.Column('management', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('desired_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_provenance', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['implementation_revision_id'], ['implementation_revisions.id'], ),
    sa.ForeignKeyConstraint(['target_scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_bindings_control_id'), 'policy_bindings', ['control_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('subject_kind', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.String(length=512), nullable=False),
    sa.Column('subject_name', sa.String(length=256), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=True),
    sa.Column('scope_id', sa.String(length=64), nullable=True),
    sa.Column('application', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=256), nullable=True),
    sa.Column('applicability', sa.String(length=16), nullable=True),
    sa.Column('configuration_result', sa.String(length=16), nullable=True),
    sa.Column('exception_disposition', sa.String(length=24), nullable=True),
    sa.Column('exception_id', sa.String(length=64), nullable=True),
    sa.Column('request_impact', sa.String(length=32), nullable=True),
    sa.Column('readiness', sa.String(length=16), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('baseline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessment_results_run_kind', 'assessment_results', ['run_id', 'subject_kind'], unique=False)
    op.create_table('delivery_targets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bundle_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('ring_stage', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_kind', sa.String(length=48), nullable=False),
    sa.Column('native_identity', sa.String(length=512), nullable=False),
    sa.Column('expected_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_digest', sa.String(length=80), nullable=False),
    sa.Column('enforcing', sa.Boolean(), nullable=False),
    sa.Column('exception_id', sa.String(length=64), nullable=True),
    sa.Column('binding_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_basis_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_receipt_id', sa.String(length=64), nullable=True),
    sa.Column('last_observation_id', sa.String(length=64), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['binding_id'], ['policy_bindings.id'], ),
    sa.ForeignKeyConstraint(['bundle_id'], ['handoff_bundles.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['rollout_plans.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_targets_bundle_id'), 'delivery_targets', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_delivery_targets_control_id'), 'delivery_targets', ['control_id'], unique=False)
    op.create_index(op.f('ix_delivery_targets_plan_id'), 'delivery_targets', ['plan_id'], unique=False)
    op.create_table('deployment_receipts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('receipt_key', sa.String(length=128), nullable=False),
    sa.Column('payload_digest', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bundle_id', sa.String(length=64), nullable=True),
    sa.Column('bundle_digest', sa.String(length=80), nullable=False),
    sa.Column('ring_stage', sa.String(length=16), nullable=True),
    sa.Column('target_scope_native_id', sa.String(length=512), nullable=False),
    sa.Column('pipeline_run_ref', sa.String(length=256), nullable=False),
    sa.Column('applied_native_identities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('reported_completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivery_target_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['handoff_bundles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_key'),
    sa.UniqueConstraint('seq')
    )
    op.create_table('observations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('delivery_target_id', sa.String(length=64), nullable=True),
    sa.Column('binding_id', sa.String(length=64), nullable=True),
    sa.Column('exception_id', sa.String(length=64), nullable=True),
    sa.Column('native_identity', sa.String(length=512), nullable=False),
    sa.Column('observed_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_digest', sa.String(length=80), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('comparison', sa.String(length=16), nullable=False),
    sa.Column('differences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applied_to_state', sa.Boolean(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['binding_id'], ['policy_bindings.id'], ),
    sa.ForeignKeyConstraint(['delivery_target_id'], ['delivery_targets.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('deployment_receipts')
    op.drop_index(op.f('ix_delivery_targets_plan_id'), table_name='delivery_targets')
    op.drop_index(op.f('ix_delivery_targets_control_id'), table_name='delivery_targets')
    op.drop_index(op.f('ix_delivery_targets_bundle_id'), table_name='delivery_targets')
    op.drop_table('delivery_targets')
    op.drop_index('ix_assessment_results_run_kind', table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_policy_bindings_control_id'), table_name='policy_bindings')
    op.drop_table('policy_bindings')
    op.drop_index(op.f('ix_implementation_validations_implementation_revision_id'), table_name='implementation_validations')
    op.drop_table('implementation_validations')
    op.drop_index(op.f('ix_handoff_bundles_package_id'), table_name='handoff_bundles')
    op.drop_index(op.f('ix_handoff_bundles_bundle_digest'), table_name='handoff_bundles')
    op.drop_table('handoff_bundles')
    op.drop_index(op.f('ix_assessment_runs_control_id'), table_name='assessment_runs')
    op.drop_table('assessment_runs')
    op.drop_index(op.f('ix_implementation_revisions_implementation_id'), table_name='implementation_revisions')
    op.drop_table('implementation_revisions')
    op.drop_index(op.f('ix_exceptions_lineage_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_control_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_change_packages_plan_id'), table_name='change_packages')
    op.drop_index(op.f('ix_change_packages_control_id'), table_name='change_packages')
    op.drop_table('change_packages')
    op.drop_index(op.f('ix_rollout_plans_control_id'), table_name='rollout_plans')
    op.drop_table('rollout_plans')
    op.drop_index(op.f('ix_readiness_evidence_control_id'), table_name='readiness_evidence')
    op.drop_table('readiness_evidence')
    op.drop_index(op.f('ix_implementations_control_id'), table_name='implementations')
    op.drop_table('implementations')
    op.drop_index(op.f('ix_control_revisions_control_id'), table_name='control_revisions')
    op.drop_table('control_revisions')
    op.drop_table('work_references')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_resource_snapshots_snapshot_id'), table_name='resource_snapshots')
    op.drop_table('resource_snapshots')
    op.drop_table('governance_settings')
    op.drop_table('controls')
    op.drop_index('ix_decisions_subject', table_name='approval_decisions')
    op.drop_table('approval_decisions')
    op.drop_table('users')
    op.drop_table('scopes')
    op.drop_table('request_fixture_sets')
    op.drop_table('inventory_snapshots')
    op.drop_index('ix_audit_object', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_control_id'), table_name='audit_events')
    op.drop_index('ix_audit_correlation', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
